version: "3.9"
services:
  postgres:
    image: postgres:13.3
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "${PORT}:${PORT}"
  
  minio:
    image: quay.io/minio/minio 
    command: 'server --console-address ":${MINIO_CONSOLE_PORT}" /data'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_storage:/data
    ports:
      - "${MINIO_API_PORT}:${MINIO_API_PORT}"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"

  redis:
    image: redis:alpine3.16
    container_name: redis-cache
    env_file: .env
    command: >
      --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: unless-stopped

volumes:
  minio_storage: {}
  postgres_storage: {}
